import React from 'react'
import YouTubePlayer from '../../../generics/youtube_player'

const CooperacaoEOPensamentoComputacional = () => (
    <div>
        <p>Certamente cada um de n&oacute;s j&aacute; tomou parte, em algum momento da vida, de uma a&ccedil;&atilde;o ou atividade onde um objetivo comum foi estabelecido e cada membro de um grupo investiu esfor&ccedil;o e/ou recursos diversos para sua concretiza&ccedil;&atilde;o. Talvez um &quot;mutir&atilde;o&quot; para revitaliza&ccedil;&atilde;o de um pr&eacute;dio ou instala&ccedil;&atilde;o de uso comum, uma a&ccedil;&atilde;o para angariar fundos para uma causa reconhecida por seus m&eacute;ritos, ou a forma&ccedil;&atilde;o de um grupo para realizar trabalhos acad&ecirc;micos na busca por compreender temas complexos, estudar para uma prova ou mesmo para se preparar para um concurso. Mais adiante o caso onde o objetivo comum &eacute; a aprendizagem. Por enquanto, vamos relembrar os exemplos apresentados ao longo do texto sobre o pilar <span className="negrito">Decomposi&ccedil;&atilde;o</span>.</p>
        <p>A <span className="negrito">Decomposi&ccedil;&atilde;o</span> pode referir-se a aspectos estruturais de um certo tema, como &eacute; o caso na atividade avaliativa 3 (Entendendo o Corpo Humano) daquela parte do texto. Em outros casos, a decomposi&ccedil;&atilde;o pode envolver caracter&iacute;sticas relacionadas &agrave; participa&ccedil;&atilde;o humana, como sugere a atividade avaliativa 2 (Organizando um Evento) da mesma parte do texto, onde est&aacute; indicada a participa&ccedil;&atilde;o de pessoas ou equipes, respons&aacute;veis por diferentes aspectos que constituem um evento. A partir deste &uacute;ltimo cen&aacute;rio, podemos enumerar alguns dos aspectos caracter&iacute;sticos da coopera&ccedil;&atilde;o:</p>
        <ol>
            <li>O sucesso de cada indivíduo e de cada grupo envolvido no evento depende do sucesso dos demais;</li>
            <li>É necessário que haja interação entre indivíduos e grupos envolvidos para ajudar que cada um cumpra sua parte no processo;</li>
            <li>Além/Apesar do interesse compartilhado, há responsabilidades individuais pelas atividades desenvolvidas;</li>
            <li>São necessárias habilidades sociais como negociação, liderança, tomada de decisão, comunicação, confiança e resolução de conflitos;</li>
            <li>O registro dos erros e acertos possibilita a reflexão sobre o quê e como o processo pode ser melhorado.</li>
        </ol>
        <p>Na animação a seguir cada um dos personagens está cooperando na tarefa de pintar a casa! O resultado final ( a casa pintada) depende da tarefa desenvolvida por cada um dos personagens que em seu diálogo demonstram sua capacidade de comunicação e interesse em atingir um objetivo comum. Características que deveriam ser replicadas no mundo real quando pessoas cooperam entre si para atingir objetivos comuns!</p>
        <YouTubePlayer videoId="OTjJVnDaUhg" />
        <p>A <span className="negrito">Decomposi&ccedil;&atilde;o</span> de um problema em partes mais elementares possibilita tornar expl&iacute;citas as tarefas requeridas para a solu&ccedil;&atilde;o de um problema, al&eacute;m de facilitar a comunica&ccedil;&atilde;o entre os atores envolvidos e a percep&ccedil;&atilde;o do progresso individual e total.</p>
        <p>Um aspecto decisivo nas a&ccedil;&otilde;es cooperativas &eacute; a distribui&ccedil;&atilde;o das tarefas a membros do grupo, que deve ser resultado do casamento entre cada tarefa a aspectos caracter&iacute;sticos ou desej&aacute;veis do agente humano respons&aacute;vel pela sua realiza&ccedil;&atilde;o. Embora possa &agrave; primeira vista parecer simples, isso envolve a identifica&ccedil;&atilde;o dos requisitos da tarefa e das caracter&iacute;sticas (habilidades, compet&ecirc;ncias, potencialidades, prefer&ecirc;ncias, etc) do agente humano envolvido. Essa necessidade de representar os elementos da realidade considerada com foco na realiza&ccedil;&atilde;o da tarefa por um agente humano &eacute; um exemplo da import&acirc;ncia do pilar <span className="negrito">Abstra&ccedil;&atilde;o</span> no planejamento de atividades cooperativas.</p>
        <p>A&ccedil;&otilde;es cooperativas necessariamente envolvem a intera&ccedil;&atilde;o entre os membros do grupo e a realiza&ccedil;&atilde;o de atividades coordenadas que s&atilde;o resultado dessas intera&ccedil;&otilde;es. H&aacute; entretanto, contextos de intera&ccedil;&atilde;o que n&atilde;o contribuem ou prejudicam o trabalho, tornando-se por isso indesej&aacute;veis - a conversa c&iacute;clica (sem avan&ccedil;os), o debate estagnado (impasse), a discuss&atilde;o desordenada, dentre v&aacute;rios outros, s&atilde;o exemplos. Identificar tais situa&ccedil;&otilde;es atrav&eacute;s dos recursos discutidos no pilar <span className="negrito">Reconhecimento de padr&otilde;es</span> tamb&eacute;m &eacute; determinante para a coopera&ccedil;&atilde;o.</p>
        <p>Ainda considerando a din&acirc;mica interacionista mencionada no &uacute;ltimo par&aacute;grafo, podemos pensar em como organiz&aacute;-la segundo um conjunto de instru&ccedil;&otilde;es precisas de passos a serem seguidos, um 'algoritmo' ou script que facilite e caracterize a a&ccedil;&atilde;o cooperativa sendo realizada, algumas vezes constituindo-se em elemento central de um &quot;m&eacute;todo&quot;.</p>
        <p>Ao longo do tempo a coopera&ccedil;&atilde;o tem sido utilizada em contextos educacionais, tendo motivado a partir dos anos 1970 o surgimento de v&aacute;rios m&eacute;todos de aprendizagem cooperativa, que s&atilde;o recursos que os professores podem fazer uso e cuja apropria&ccedil;&atilde;o pode ser apoiada pelos pilares - usualmente cada m&eacute;todo &eacute; estruturado em etapas (decomposi&ccedil;&atilde;o), desenvolve suas din&acirc;micas segundo certos scripts (algoritmos), t&ecirc;m pap&eacute;is ou fun&ccedil;&otilde;es espec&iacute;ficos (reconhecimento de padr&otilde;es) e tem foco e prioridade em aspectos espec&iacute;ficos (abstra&ccedil;&atilde;o).</p>
        <p>M&eacute;todos de aprendizagem cooperativa podem tamb&eacute;m ser investigados segundo uma linha paradigm&aacute;tica que vem sendo denominada Arquitetura Pedag&oacute;gica (AP), que busca pensar propostas pedag&oacute;gicas em sintonia com as possibilidades oferecidas pela tecnologia. Nessa perspectiva ao inv&eacute;s de olharmos uma proposta pedag&oacute;gica concebida independentemente dos elementos tecnol&oacute;gicos e tentarmos inserir a tecnologia, consideramos os dois aportes para pensar novas solu&ccedil;&otilde;es. As AP podem ser caracterizadas segundo elementos essenciais: dom&iacute;nio de conhecimento, objetivos educacionais, conhecimento pr&eacute;vio, din&acirc;micas interacionista-problematizadoras, media&ccedil;&otilde;es pedag&oacute;gicas distribu&iacute;das, avalia&ccedil;&atilde;o processual e cooperativa das aprendizagens, suporte computacional (decomposi&ccedil;&atilde;o). As din&acirc;micas interacionistas s&atilde;o caracterizadas segundo esquemas diversos (algoritmos) e pressup&otilde;em uma postura ativa, pesquisa, atividades interativas e autorais com apoio em suportes inform&aacute;ticos e abordagens problematizadoras por parte do professor (abstra&ccedil;&atilde;o). A caracteriza&ccedil;&atilde;o de requisitos para o suporte inform&aacute;tico (reconhecimento de padr&otilde;es), que integra a defini&ccedil;&atilde;o das AP, constitui elemento norteador para as novas gera&ccedil;&otilde;es tecnol&oacute;gicas. </p>
    </div>
)

export default CooperacaoEOPensamentoComputacional