import React from 'react'

const Texto1 = () => (
    <div>
        <p>Desde os prim&oacute;rdios de sua hist&oacute;ria, a humanidade busca construir <strong>tecnologias para apoiar a resolu&ccedil;&atilde;o dos problemas</strong> com os quais se depara, inicialmente para sobreviver &agrave;s intemp&eacute;ries da natureza e para garantia da alimenta&ccedil;&atilde;o, nos dias atuais, para garantia da qualidade de vida individual e coletiva, o conv&iacute;vio pac&iacute;fico e o respeito &agrave; natureza. Para tal, al&eacute;m da inven&ccedil;&atilde;o das tecnologias f&iacute;sicas, passou a conceber tamb&eacute;m tecnologias intelectuais.</p>        <p>Alguns exemplos interessantes:</p>
        <p>Muito j&aacute; foi descoberto e inventado, em favor de melhores dias, no campo da alimenta&ccedil;&atilde;o, da sa&uacute;de, da preven&ccedil;&atilde;o e supera&ccedil;&atilde;o dos desastres naturais, dos transportes etc. Todas essas descobertas compartilham um princ&iacute;pio importante, a busca pelo uso econ&ocirc;mico (evitando desperd&iacute;cio, principalmente do que for escasso) do tempo, do espa&ccedil;o, dos recursos naturais (principalmente os n&atilde;o-renov&aacute;veis) e, at&eacute; mesmo, dos recursos financeiros, individuais e coletivos.</p>
        <p>Diversas metodologias que s&atilde;o usadas para apoiar a resolu&ccedil;&atilde;o de problemas compartilham um conjunto de elementos importantes que est&atilde;o sistematizados no que veio a ser conhecido como <strong>Pensamento Computacional</strong>.</p>
        <p><strong>Pensamento Computacional</strong> pode ser visto como sendo um processo de pensamento para encontrar e especificar solu&ccedil;&otilde;es para problemas, de tal forma que seres humanos ou computadores possam resolv&ecirc;-los.</p>
        <p>A aplica&ccedil;&atilde;o pr&aacute;tica de Pensamento Computacional pode ser observada tanto na resolu&ccedil;&atilde;o de problemas b&aacute;sicos do cotidiano, como no planejamento das compras de uma fam&iacute;lia, quanto na resolu&ccedil;&atilde;o de problemas mais complexos, como na concep&ccedil;&atilde;o de um sistema escolar, na log&iacute;stica de uma rede de abastecimento, na elabora&ccedil;&atilde;o de um sistema de preven&ccedil;&atilde;o e erradica&ccedil;&atilde;o de epidemias ou no envio de uma nave espacial para a Lua.</p>
        <p>No decorrer da hist&oacute;ria da humanidade, alguns momentos importantes introduziram grandes transforma&ccedil;&otilde;es com fortes influ&ecirc;ncias em nosso modo de viver. No s&eacute;culo XX, o forte desenvolvimento de Ci&ecirc;ncia e Tecnologia deu origem a atividades relacionadas com a coleta, processamento e an&aacute;lise de informa&ccedil;&atilde;o, requerendo novas compet&ecirc;ncias e dando origem ao termo &ldquo;Sociedade do Conhecimento&rdquo;, que se caracteriza por uma maior preocupa&ccedil;&atilde;o com o capital intelectual dos cidad&atilde;os.</p>
        <p>Embora as preocupa&ccedil;&otilde;es com o uso econ&ocirc;mico de recursos j&aacute; estejam presente h&aacute; muito tempo em nossa hist&oacute;ria, s&oacute; mais recentemente ganharam destaque em nosso cotidiano, em consequ&ecirc;ncia do deslocamento do tipo de atividades que passamos a exercer em um mundo onde o trabalho mec&acirc;nico est&aacute; cada vez mais sendo transferido para as m&aacute;quinas.</p>
        <p>Desde a d&eacute;cada de 50 do s&eacute;culo passado, as preocupa&ccedil;&otilde;es com pensamento computacional j&aacute; estavam presente nos trabalhos de George Polya (&ldquo;A Arte de Resolver Problemas&rdquo;) e mais tarde com Seymour Papert, em seu livro &ldquo;Mindstorm&rdquo;. Mais recentemente, no in&iacute;cio do s&eacute;culo XXI, teve origem um movimento internacional pela inclus&atilde;o nos sistemas escolares da prepara&ccedil;&atilde;o dos cidad&atilde;os para a resolu&ccedil;&atilde;o de problemas com o uso de Pensamento Computacional. Um artigo da pesquisadora norte-americana Jannete Wing &eacute; um marco nesse movimento.</p>
        <p>Neste curso iremos tratar do que tem sido chamado os 4 Pilares do Pensamento Computacional, a saber: <strong>Abstra&ccedil;&atilde;o</strong>, <strong>Decomposi&ccedil;&atilde;o</strong>, <strong>Reconhecimento de Padr&otilde;es</strong> e <strong>Algoritmos</strong>. Antes de prosseguirmos, vamos examinar dois exemplos de problemas cujo processo de busca de solu&ccedil;&otilde;es pode beneficiar-se enormemento do Pensamento Computacional.</p>
    </div>
)

export default Texto1
